[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "colorfingerprint"
version = "0.1.0"
description = "my colorfingerprint"
requires-python = ">=3.8"

[project.scripts]
clrfp = "colorfingerprint.cli:main"